version: "3.8"

services:
  react-app:
    image: node
    working_dir: /app
    command: sh -c "yarn install && yarn start"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./public:/app/public
    ports:
      - "4000:3000"
    environment: { CHOKIDAR_USEPOLLING: "true" }
