version: "3.8"

services:
  react-app:
    image: node
    working_dir: /app
    command: sh -c "yarn global add npm@7.4.0 && npm install && npm start"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./webpack.config.js:/app/webpack.config.js
      - ./.babelrc:/app/.babelrc
      - ./.dockerignore:/app/.dockerignore
    ports:
      - "3002:3000"
    environment: { CHOKIDAR_USEPOLLING: "true" }
